#!/usr/bin/env ruby

require 'rubygems'
require 'eventmachine'
puts "EventMachine Loaded"

ROOT=File.dirname(__FILE__)
puts "ROOT set to '#{ROOT}'"

DIST="#{ROOT}/dist"
puts "DIST set to '#{DIST}'"

require "#{ROOT}/lib/meth.rb"
puts "Meth Loaded"

EM.epoll
EM.run {
  begin
    puts "Connecting MethBot to #{Meth::Bot.server}:#{Meth::Bot.port.to_s}"
    EM::connect(Meth::Bot.server, Meth::Bot.port, Meth::Bot)
  rescue
    puts "Error: #{$!}"
    $@.each do |line| puts "#{line}" end
  end
}

