#!/usr/bin/env ruby

=begin
Check Parameters
=end

if ARGV[0].nil?
  puts "Missing bot name argument."
  exit
end

=begin
Globals
=end

ROOT  = File.dirname(__FILE__)
DIST  = "#{ROOT}/dist"
BOT   = "#{DIST}/bots/#{ARGV[0]}"

=begin
Load Path
=end

$: << "#{ROOT}/lib/"

=begin
Main Libs
=end

require 'rubygems'
require 'eventmachine'
require 'logger'
require 'yaml'

require "meth/meth.rb"

Dir[
  "#{DIST}/lib/*.rb",
  "#{DIST}/lib/*.so",
  "#{DIST}/models/*.rb",
  "#{BOT}/lib/*.rb",
  "#{BOT}/models/*.rb"
].each { |m| require m if FileTest.executable?(m) }

CONFIG = YAML.load(File.open("#{BOT}/conf/settings.yaml"))


=begin
Run
=end

EM::run {
  begin
    EM::connect(CONFIG['server'],CONFIG['port'],Meth::Bot)
  rescue
    puts "#{$!}\n#{$@.join("\n")}"
    exit 1
  end
}

