#!/usr/bin/env ruby

=begin
Globals
=end

ROOT  = File.dirname(__FILE__)

CONFIG = YAML.load(File.open("#{ROOT}/conf/settings.yaml"))

LOGGER = Logger.new("#{ROOT}/logs/#{CONFIG['name']}")
LOGGER.level = Logger.const_get(CONFIG['logger']['severity'])


=begin
Load Path
=end

$: << "#{ROOT}/lib/"

=begin
Main Libs
=end

require 'rubygems'
require 'eventmachine'
require 'logger'
require 'yaml'

Dir[
  "#{ROOT}/lib/*.rb",
  "#{ROOT}/models/*.rb",
].each { |m| require m if FileTest.executable?(m) }

require "meth/meth.rb"




=begin
Run
=end

EM::run {
  begin
    EM::connect(CONFIG['server'],CONFIG['port'],Meth::Bot)
  rescue
    puts "#{$!}\n#{$@.join("\n")}"
    exit 1
  end
}

